dev_resource_group_name = "DEV-RG"
dev_location = "Central US"
dev_vnet_name = "DEV-VNET"
dev_app_nsg_name = "DEV-APP-NSG"
dev_db_nsg_name = "DEV-DB-NSG"
dev_vnet_address_space = ["10.1.0.0/16"]
dev_app_subnet_name = "DEV-APP"
dev_app_subnet_address_prefix = ["10.1.0.0/28"]
dev_db_subnet_name = "DEV-DB"
dev_db_subnet_address_prefix = ["10.1.0.16/28"]
dev_app_service_plan_name = "DEV-APP-PLAN"
dev_app_service_name = "DEV-APP-POC-01"
dev_dns_zone= "dev.postgres.database.azure.com"
dev_dns_zone_link= "devVnetZone.com"
dev_sql_name= "devpocsqlflexibleserver02"
dev_acr_name= "devacrpoc02"
dev_storage_account_name= "devpocstorage02"
